### ISSUE TITLE
Replicate the project

### ISSUE THREAD

**Issue by zouyuwuse** [Mrliukuang/FER2#1]
我下载了你的MATLAB代码与论文。在仔细研究了论文之后，在MATLAB 上运行的过程中。跑不出结果。想请教一下，你的代码结构是怎么样的。怎样才能跑起来。另外FER2013这个数据集我下载后是.csv文件。请问你的图片数据是在哪里下载的。麻烦告知一下，谢谢了！

**Comment by kuangliu** [comment]
1. It's not easy to run this code. It's a CNN learning project, and it's poorly organized. 
2. It should be still functional, but needs to be carefully tweaked.
3. I highly recommend you to reimplement the model with Torch [ConcatTable](https://github.com/torch/nn/blob/master/doc/table.md#concattable).
4. The .csv file actually contains the image information. The number is the grayscale value.
